/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {Message, ResponseChat, SwitchInfluenceStyle, UserMetadata} from "./types"
import type TypeBuilder from "./type_builder"

type BamlCallOptions = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  Betty(
      instruction: string,messages: Message[],relevant_feedbacks: string,user_metadata: UserMetadata,user_memory: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "Betty",
        {
          "instruction": instruction,"messages": messages,"relevant_feedbacks": relevant_feedbacks,"user_metadata": user_metadata,"user_memory": user_memory
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InitialMessageChat(
      instruction: string,relevant_feedbacks: string,user_influence_style: string,user_memory: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "InitialMessageChat",
        {
          "instruction": instruction,"relevant_feedbacks": relevant_feedbacks,"user_influence_style": user_influence_style,"user_memory": user_memory
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  Betty(
      instruction: string,messages: Message[],relevant_feedbacks: string,user_metadata: UserMetadata,user_memory: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "Betty",
        {
          "instruction": instruction,"messages": messages,"relevant_feedbacks": relevant_feedbacks,"user_metadata": user_metadata,"user_memory": user_memory
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InitialMessageChat(
      instruction: string,relevant_feedbacks: string,user_influence_style: string,user_memory: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "InitialMessageChat",
        {
          "instruction": instruction,"relevant_feedbacks": relevant_feedbacks,"user_influence_style": user_influence_style,"user_memory": user_memory
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}