/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  Message,  ResponseChat,  SwitchInfluenceStyle,  UserMetadata } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "Betty" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } instruction - Input parameter.
 * @param { Message[] } messages - Input parameter.
 * @param { string } relevant_feedbacks - Input parameter.
 * @param { UserMetadata } user_metadata - Input parameter.
 * @param { string } user_memory - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const Betty = async (
  instruction: string,
  messages: Message[],
  relevant_feedbacks: string,
  user_metadata: UserMetadata,
  user_memory: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.Betty(
    instruction,
    messages,
    relevant_feedbacks,
    user_metadata,
    user_memory,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "InitialMessageChat" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } instruction - Input parameter.
 * @param { string } relevant_feedbacks - Input parameter.
 * @param { string } user_influence_style - Input parameter.
 * @param { string } user_memory - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const InitialMessageChat = async (
  instruction: string,
  relevant_feedbacks: string,
  user_influence_style: string,
  user_memory: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.InitialMessageChat(
    instruction,
    relevant_feedbacks,
    user_influence_style,
    user_memory,
  );
  return Promise.resolve(stream.toStreamable());
};